### PR TITLE
#80 - Check that raffle has eligible comments

### LINKED ISSUE #80: Check that raffle has eligible comments
We should not be able to start a raffle if there are no comments in picked events.

Dont forget to implement it on API and show the error on frontend too!

### PR DESCRIPTION
**Pull request by HcsOmot**
We actually already have this functionality implemented, but have't realized it until adding new scenarios and step implementations.

Having problems with unit tests again, tho.

Closes #80

### CODE REVIEW

**Comment by HcsOmot** [comment]
fixed, all green. please review.

**Review by msvrtan — APPROVED** [review]
👍

**Comment by HcsOmot** [comment]
hey @msvrtan, I apologize, but could you review again, please? I noticed some last minute errors (failed to implement some features), so I squashed some new commits that weren't there before. Sorry!

**Comment by HcsOmot** [comment]
hint: all changes were squashed into commit 9a3097dfe106d

**Review by msvrtan — APPROVED** [review]
Good one! 👍

**Pull request merged**
