### PR TITLE
#79 - Check that a raffle has events selected

### PR DESCRIPTION
**Pull request by HcsOmot**
Define scenario for raffle with no events selected

Since the raffle can't start without events
In order to cover such edge cases
And to better describe our business requirements
We need defined scenarios and their step implementations
    
I've defined the required scenario and step implementation for RaffleContext and implemented the logic for handling such Raffle cases.

Handle no event raffle case in context of Raffle API
    
We need to make sure Raffle API context handles requests for a raffle with no provided events in a proper way.
    
RaffleApiContext implements the step for a scenario when a raffle is requested, but no events are provided.
    
RaffleApiController returns appropriate message in such cases.

**[PROBLEM]**
- having trouble writing PhpUnit tests for Raffle. Also, phpmd-task is complaining about to many coupling between objects in RaffleApiController.

### CODE REVIEW

**Comment by msvrtan** [comment]
Pushed 'fixes' for all 3 problems, each is it's own commit

**Comment by HcsOmot** [comment]
👍 looks good to me. shall I merge it as is, or do I squash to previous matching commits?

**Comment by msvrtan** [comment]
No, lets leave it in peace for the meetup today

**Review by msvrtan — APPROVED** [review]
👍

**Pull request merged**
